[package]
name = "grocer"
version = "0.1.1"
edition = "2021"
description = "A simple Rust library for reading UPC barcodes from images."
license = "BSD-2-Clause"
keywords = ["barcode", "upc", "scan", "images"]
readme = "README.md"


[dependencies]
image = "0.25.1"
